import "../lib/theme/global.css";

import SiteHeader from "@components/layout/SiteHeader";
import SiteFooter from "@components/layout/SiteFooter";

import { Ibarra_Real_Nova, Public_Sans } from "next/font/google";

const IbarraRealNova = Ibarra_Real_Nova({
  subsets: ["latin"],
  variable: "--font-ibrarra-real-nova",
});

const PublicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-public-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${IbarraRealNova.variable} ${PublicSans.variable}`}
    >
      <body>
        <SiteHeader />
        {children}
        <SiteFooter />
      </body>
    </html>
  );
}
